version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ${PATH_SRC}/ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net

  post:
    build: ${PATH_SRC}/post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net

  comment:
    build: ${PATH_SRC}/comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - back_net
      - front_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
