---
- name: Deploy k8s master node
  hosts: all
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm --apiserver-cert-extra-sans={{ master_host }} --apiserver-advertise-address=0.0.0.0 --control-plane-endpoint={{ master_host }} init --pod-network-cidr=10.244.0.0/16
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

#    - name: Initialize the Kubernetes cluster using kubeadm
#      command: kubeadm init --apiserver-advertise-address= --apiserver-cert-extra-sans="192.168.50.10

#      "sudo kubeadm init --apiserver-cert-extra-sans=${self.network_interface.0.nat_ip_address}
#       --apiserver-advertise-address=0.0.0.0 --control-plane-endpoint=${self.network_interface.0.nat_ip_address}
#       --pod-network-cidr=10.244.0.0/16",

    - name: create .kube directory
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755


    - name: copies admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu


    - name: download calcio.yml
      become_user: ubuntu
      get_url:
        url: https://docs.projectcalico.org/archive/v3.19/manifests/calico.yaml
        dest: $HOME/

    - name: install Pod network
      shell: kubectl apply -f /home/ubuntu/calico.yaml

    - name: Get the token for joining the worker nodes
      become: yes
      become_user: ubuntu
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - name: Print join command
      debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      become: no
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
