---
- name: Deploy k8s master node
  hosts: all
  become: yes
  vars_files:
    - hosts_variables.yml
  tasks:

    - name: initialize the cluster
      shell: "kubeadm --apiserver-cert-extra-sans={{ ansible_host }} --apiserver-advertise-address=0.0.0.0 --control-plane-endpoint={{ ansible_host  }} init --pod-network-cidr=10.244.0.0/16"
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copies admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: Copy system settings files.
      copy:
        src: calico.yaml
        dest: /home/ubuntu/

    - name: Copy files with reddit.
      copy:
        src: reddit
        dest: /home/ubuntu/
        directory_mode: yes

    - name: install Pod network
      become_user: ubuntu
      shell: kubectl apply -f /home/ubuntu/calico.yaml

    - name: Get the token for joining the worker nodes
      become: yes
      shell: kubeadm token create --print-join-command
      register: kubernetes_join_command # регистрация переменной

    - name: Print join command
      debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Deligate to ...
      become: yes
      command: "{{ kubernetes_join_command.stdout }}"
      delegate_to: "{{ worker_host }}"
